apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    service: mongo-deploy
spec:
  selector:
    matchLabels:
      service: mongo-deploy
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo-deploy
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    service: mongo-deploy
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
